services:
    _defaults:
        autowire: true
        autoconfigure: true

    Pitch\Liform\Extension\AttrExtension:
        tags:
            - { name: liform.extension }

    Pitch\Liform\Extension\DisabledExtension:
        tags:
            - { name: liform.extension }

    Pitch\Liform\Extension\ErrorExtension:
        tags:
            - { name: liform.extension }

    Pitch\Liform\Extension\HelpExtension:
        tags:
            - { name: liform.extension }

    Pitch\Liform\Extension\LabelExtension:
        tags:
            - { name: liform.extension }

    Pitch\Liform\Extension\ValueExtension:
        tags:
            - { name: liform.extension }

    Pitch\Liform\Extension\WidgetExtension:
        tags:
            - { name: liform.extension }

