services:
    _defaults:
        autowire: true
        autoconfigure: true

    Pitch\Liform\ResolverInterface:
        alias: Pitch\Liform\Resolver

    Pitch\Liform\Resolver:

    Pitch\Liform\LiformInterface:
        class: Pitch\Liform\Liform
