services:
    _defaults:
        autowire: true
        autoconfigure: true

    Pitch\Liform\Transformer\ArrayTransformer:
        tags:
            - { name: liform.transformer, block: collection }

    Pitch\Liform\Transformer\BooleanTransformer:
        tags:
            - { name: liform.transformer, block: checkbox }

    Pitch\Liform\Transformer\ButtonTransformer:
        tags:
            - { name: liform.transformer, block: button }

    Pitch\Liform\Transformer\ChoiceTransformer:
        tags:
            - { name: liform.transformer, block: choice }

    Pitch\Liform\Transformer\CompoundTransformer:
        tags:
            - { name: liform.transformer, block: form }

    Pitch\Liform\Transformer\DateTimeTransformer:
        tags:
            - { name: liform.transformer, block: datetime }
            - { name: liform.transformer, block: dateinterval }
            - { name: liform.transformer, block: date }
            - { name: liform.transformer, block: time }
            - { name: liform.transformer, block: week }

    Pitch\Liform\Transformer\NumberTransformer:
        tags:
            - { name: liform.transformer, block: number }
            - { name: liform.transformer, block: integer }
            - { name: liform.transformer, block: range }
            - { name: liform.transformer, block: money }
            - { name: liform.transformer, block: percent }

    Pitch\Liform\Transformer\StringTransformer:
        tags:
            - { name: liform.transformer, block: text }
            - { name: liform.transformer, block: textarea }
            - { name: liform.transformer, block: color }
