services:
    _defaults:
        autowire: true
        autoconfigure: true

    Pitch\Liform\Transformer\AbstractTransformer:
        abstract: true
        arguments:
            $validatorGuesser: '@Pitch\Liform\Guesser\ValidatorGuesser'

    Pitch\Liform\Transformer\BooleanTransformer:
        parent: Pitch\Liform\Transformer\AbstractTransformer
        tags:
            - { name: liform.transformer, form_type: checkbox, widget: checkbox }

    Pitch\Liform\Transformer\ArrayTransformer:
        parent: Pitch\Liform\Transformer\AbstractTransformer
        tags:
            - { name: liform.transformer, form_type: collection }

    Pitch\Liform\Transformer\ChoiceTransformer:
        parent: Pitch\Liform\Transformer\AbstractTransformer
        tags:
            - { name: liform.transformer, form_type: choice }

    Pitch\Liform\Transformer\CompoundTransformer:
        parent: Pitch\Liform\Transformer\AbstractTransformer
        tags:
            - { name: liform.transformer, form_type: compound }

    Pitch\Liform\Transformer\IntegerTransformer:
        parent: Pitch\Liform\Transformer\AbstractTransformer
        tags:
            - { name: liform.transformer, form_type: integer }

    Pitch\Liform\Transformer\NumberTransformer:
        parent: Pitch\Liform\Transformer\AbstractTransformer
        tags:
            - { name: liform.transformer, form_type: number }

    Pitch\Liform\Transformer\StringTransformer:
        parent: Pitch\Liform\Transformer\AbstractTransformer
        tags:
            - { name: liform.transformer, form_type: text }
            - { name: liform.transformer, form_type: email, widget: email }
            - { name: liform.transformer, form_type: money, widget: money }
            - { name: liform.transformer, form_type: password, widget: password }
            - { name: liform.transformer, form_type: percent, widget: percent }
            - { name: liform.transformer, form_type: search, widget: search }
            - { name: liform.transformer, form_type: textarea, widget: textarea }
            - { name: liform.transformer, form_type: time, widget: time }
            - { name: liform.transformer, form_type: url, widget: url }
